### ISSUE TITLE
Thermostat card, no temp, inactive icon and progress bar of temp

### ISSUE THREAD

**Issue by alexreddy78** [shroom-singles/thermostat#4]
Dear Developer

Card doesn't show temp set, says NaN C, as well icon of thermostat is not changing status (on, off, shows always grey) and progress bar of temp as well in grey
My thermostat attributes below:

hvac_modes:
  - 'off'
  - auto
  - heat
min_temp: 7
max_temp: 35
target_temp_step: 0.5
current_temperature: 25.5
temperature: 18
friendly_name: Floor
supported_features: 1

**Comment by ulic75** [comment]
Hey, I'm glad you found this addon card.  First question, you are running the official Mushroom package as well correct?  It won't work without it. Thank you for supplying the attributes.  What is the state?  Does the state change on your device when it is heating versus idle?

When I used your attributes and set the state to heat I received these results.

![Screen Shot 2022-04-29 at 9 30 33 AM](https://user-images.githubusercontent.com/5641964/165977667-6cbbe0ee-1217-404c-adcf-52bfcf7c5f3b.png)

**Comment by alexreddy78** [comment]
Yes, latest version of Mushroom cards and Themes. Yes, status changed to heat, but no temp shown 25.5C, no progress orange bar, no actual temp shown 18C

Tried to redownload card and Mushroom - didnt bring results :(

However HA thermostat card shows all well

**Comment by alexreddy78** [comment]
Dear,

Issue is closed. I found solution, numbers must be set in imperial way 25,5, but not with coma 25.5

BRGDS

**Comment by ulic75** [comment]
> Issue is closed. I found solution, numbers must be set in imperial way 25,5, but not with coma 25.5

Ah, okay, interesting.  Yes.  I changed my number formatting from 1,234,567.89 to 1.234.567,89 and it broke as you described.  I'll investigate this.

**Comment by alexreddy78** [comment]
Dear,

Have to reopen issue, due to inactive icon color of thermostat and shape of that. Always show in grey, no matter is thermostat is heating, cooling, on or off. I think it should work and show color according to the state of thermostat.

Pls advise

BRGDS

**Comment by alexreddy78** [comment]
Dear Developer,

Kindly advise on above mentioned problem with actual icon color. As well after today upgrade to 1.7.3 latest version, bug with transparent fill color of card is still exist.

BRGDS

Alex

**Comment by ulic75** [comment]
I just re-released v1.7.3-thermostat.2 which should fix the missing background color.  Can you please supply two sets of the attributes and state, one set when your device is heating and another set when it is idle?

**Comment by alexreddy78** [comment]
Dear,
 Can confirm that bug with transparent card is fixed. well done!
Pls see 

hvac_modes:
  - 'off'
  - auto
  - heat
min_temp: 7
max_temp: 35
target_temp_step: 0.5
current_temperature: 27
temperature: 29
friendly_name: Теплые полы
supported_features: 1


Attributes are always the same

Status just changes to heat or off. Dont have status idle

Pls advise

**Comment by ulic75** [comment]
Thank you.  Currently things are working as designed.  The option currently supports colors and icons for Actions.  Some integrations have an attribute called hvac_action which reports things like `heating` or `cooling`.  It appears that the integration for your thermostat doesn't include that.

As I have time I'll see if I can add support for state icons/colors when hvac_action is not support.  I built this card a hobby though and can only work on it from time to time, so I have no idea how fast I'd be able to implement this new feature.

**Comment by alexreddy78** [comment]
Thanks for answer! Got it. Hope it happens :) or may be climate card will be released earlier by mushrooms developer.

Regards

**Comment by ulic75** [comment]
Icon and color when hvac_action not support are resolved in https://github.com/ulic75/lovelace-mushroom/pull/9

**Comment by alexreddy78** [comment]
@ulic75 Dear Developer,
Was is fixed? Does it mean that fix can be used? Kindly advise how to use fix

REGARDS

**Comment by ulic75** [comment]
It's fixed, but not yet released. When you see it in the release notes in
HACS it will be available. It uses the same two options as the current
action icon and action icon color.

**Comment by alexreddy78** [comment]
Dear Ulic75,

Seems to be that many of users doesn't like the way like your shroom card for thermostat is handle temp control by slider :(
Probably pittaya will not merge it...but lets see...
If fix for non hvac_action thermostats is done in PR for mushrooms, would it be possible to do same for your FANTASTIC Shroom card? Will be really nice

Regards

**Comment by ulic75** [comment]
It was released an hour ago in v1.8.0-thermostat.0

**Comment by alexreddy78** [comment]
Fantastic! Best!
